apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels: #Need to add this label for cis to ingressLink to detect
    app: nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: readiness-port 
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
