kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-hello-world-http-app-configmap
  namespace: default
  labels:
  #Note that mypartition-name, myhttp-vs, and web_pool names below must match the label in the k8 service yaml file.
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "A1 Template",
            "mypartition-name": {
                "class": "Tenant",
                "myhttp-vs": {
                    "class": "Application",
                    "template": "generic",
                    "myvs-name": {
                        "class": "Service_HTTP",
                        "remark": "a1",
                        "virtualAddresses": [
                            "???vs-ip-address???"
                        ],
                        "pool": "web_pool"
                    },
                    "web_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
